language: node_js
sudo: false
node_js: 6
before_script:
  - npm install -g gulp
script:
  - gulp
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  on:
    branch: master
